### ISSUE TITLE
Export to CSV only selected rows by default

### ISSUE THREAD

**Issue by Jenselme** [institut-de-genomique/Ultimate-DataTable#16]
Hi,

Currently, the export CSV button exports all rows. I think it would be better from a user experience point of view to only export the selected rows. What do you think? Is there an easy way to do this?

**Comment by galbini** [comment]
Hi,

This feature has designed to export all the result of a search from a server or in local. 
In fact, the user search some items with some filters and then export the result. With UDT you can plug easily a html form with the search function.

Your request is not simple because when a user selected a line on a page and then he go to another page we lost the previous selection. Export only the select on current page is not very interesting.

In this context, it's difficult for me to implement your request, the better way is to use search function or filter function to limit the result number.

**Comment by Jenselme** [comment]
OK, I just wanted to know. It is not really important and I think that filters will be enough. Thanks anyway.

**Comment by dinkar2010** [comment]
add export extension to export selected {
                            extend: 'csvHtml5',
                            text: 'Export Selected',
                            exportOptions: {
columns: ':visible',  
                                modifier: {
                                    selected: true   
                                },
                            }
 select: {               //multi select
                        style: 'multi',
                    },
